# Generated by Django 4.1 on 2022-08-16 13:07

import books.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_file',
            field=models.FileField(upload_to=books.models.books_pdf_file_path, verbose_name='livro', null=False, blank=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='book_cover',
            field=models.ImageField(default='book_default_img.jpg', upload_to=books.models.books_image_file_path, verbose_name='Capa do livro'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_description',
            field=models.CharField(max_length=400, verbose_name='Descrição do livro'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Proprietário do livro'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_title',
            field=models.CharField(max_length=50, verbose_name='Título do livro'),
        ),
    ]
