# Generated by Django 4.1 on 2022-08-16 13:26

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_book_file_alter_books_book_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_cover',
            field=models.ImageField(upload_to=books.models.books_image_file_path, verbose_name='Capa do livro'),
        ),
    ]
