# Generated by Django 4.1 on 2022-08-16 20:48

import books.models
import books.pdf_file_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_books_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_file',
            field=models.FileField(upload_to=books.models.books_pdf_file_path, validators=[books.pdf_file_validator.pdf_format_validator], verbose_name='livro'),
        ),
    ]
