# Generated by Django 4.1 on 2022-08-28 22:15

import books.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0006_authors_rename_book_cover_books_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='upload_by',
        ),
        migrations.AddField(
            model_name='authors',
            name='image',
            field=models.ImageField(default='author_default_img.jpg', verbose_name='Imagem do autor'),
        ),
        migrations.AddField(
            model_name='books',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
            preserve_default=False,
        ),
    ]
