# Generated by Django 4.1 on 2022-09-06 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_books_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publicado no site em'),
        ),
    ]
