# Generated by Django 4.1 on 2022-12-31 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_books_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registado em'),
        ),
    ]
