# Generated by Django 4.1 on 2023-01-17 13:21

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_authors_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='image',
            field=models.ImageField(upload_to=books.models.authors_image_file_path, verbose_name='Imagem do autor'),
        ),
    ]
