# Generated by Django 4.2.7 on 2024-08-30 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_authors_registration_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name_plural': 'Books'},
        ),
    ]
