# Generated by Django 4.1 on 2023-01-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_authors_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nome do autor'),
        ),
    ]
