# Generated by Django 4.2.7 on 2024-08-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_books_is_sale_books_price_books_sale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
    ]
