# Generated by Django 4.2.16 on 2024-11-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_booklists'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booklists',
            options={'verbose_name_plural': 'Book lists'},
        ),
        migrations.AlterField(
            model_name='booklists',
            name='books',
            field=models.ManyToManyField(related_name='book_lists', to='books.books', verbose_name='Livros'),
        ),
    ]
