# Generated by Django 4.2.16 on 2024-11-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_alter_booklists_options_alter_booklists_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklists',
            name='books',
            field=models.ManyToManyField(default=[0], related_name='book_lists', to='books.books', verbose_name='Livros'),
        ),
    ]
