# Generated by Django 4.2.16 on 2024-11-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_alter_authors_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklists',
            name='books',
            field=models.ManyToManyField(default=[0], related_name='book_lists', to='books.books', verbose_name='Livros'),
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.ManyToManyField(default=[0], related_name='books_category', to='books.category'),
        ),
    ]
