# Generated by Django 4.2.16 on 2024-11-28 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_alter_booklists_books_alter_books_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklists',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da ultima actualização'),
        ),
    ]
