# Generated by Django 4.2.16 on 2024-12-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0029_books_comment_alter_books_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='Comment',
            new_name='comment',
        ),
    ]
