# Generated by Django 4.2.16 on 2024-12-23 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0030_rename_comment_books_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo do anúncio')),
                ('image', models.ImageField(upload_to='announcement', verbose_name='Anúncios')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do upload')),
            ],
        ),
    ]
