# Generated by Django 4.2.16 on 2024-12-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0031_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='description',
            field=models.TextField(default='', max_length=100, verbose_name='Descrição'),
        ),
    ]
