# Generated by Django 4.2.16 on 2024-12-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0033_alter_announcement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(upload_to='announcement', verbose_name='Imagem'),
        ),
    ]
