# Generated by Django 4.2.16 on 2024-12-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0034_alter_announcement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
