# Generated by Django 4.2.16 on 2025-02-24 20:15

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0035_alter_books_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(default='unknow', max_length=50, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[books.models.val_cannot_be_negative]),
        ),
        migrations.AlterField(
            model_name='books',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, validators=[books.models.val_cannot_be_negative]),
        ),
        migrations.DeleteModel(
            name='Authors',
        ),
    ]
