# Generated by Django 4.1 on 2022-11-28 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_delete_downloadhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeBookUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='adicionado em')),
            ],
        ),
    ]
