# Generated by Django 4.1 on 2022-11-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freebookuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
