# Generated by Django 4.2.7 on 2024-09-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_invoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='invoice_file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
