# Generated by Django 4.2.7 on 2024-09-25 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_invoices_invoice_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payment.order'),
            preserve_default=False,
        ),
    ]
