# Generated by Django 4.2.7 on 2024-09-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_invoices_invoice_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='invoice_number',
            field=models.CharField(max_length=10, verbose_name='Fatura nº'),
        ),
    ]
