# Generated by Django 4.2.7 on 2024-09-30 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_invoices_invoice_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payment.order'),
        ),
    ]
