# Generated by Django 4.2.16 on 2024-12-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_remove_shippingaddress_shipping_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_mode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Local de entrega'),
        ),
    ]
