# Generated by Django 4.2.16 on 2024-12-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_alter_shippingaddress_shipping_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='payment_mode',
            field=models.CharField(default='TPA - Terminal de Pagamento Automático', max_length=100, verbose_name='Método de pagamento'),
        ),
    ]
